#!/usr/bin/env python3
"""Verify the cross-language SEAM invariants of a polyglot-core monorepo.

polyglot-core-standard is a *meta-standard*: it governs the seams BETWEEN languages
(one canonical Rust core → derived bindings → thin hosts → one composed gate), and
delegates each language's internals to the sibling standards (rust/swift/python-
project-standard). This script therefore checks only what the per-language checkers
cannot see — the seam invariants — and points you at the sibling checkers for the rest.

It is DISCOVERY-based, not layout-hard-coded: real repos do not use the template's
core/+apple/+python/ names. So it finds the Cargo workspace(s), scans for files whose
header marks them machine-generated (UniFFI / cbindgen / @generated), and heuristically
locates Swift/Python/Kotlin host sub-trees, then checks:

  HARD (✗ fails the run):
    1. a single canonical core (Cargo workspace) is identified
    2. the binding generator (uniffi / pyo3) is pinned in the core's Cargo.toml
    3. every generated binding is BOTH linguist-generated AND lint/gate-excluded
    4. a composed top-level gate (make/just/ci) chains core + host + binding-freshness
    5. a binding-freshness drift guard exists and is wired into the gate
    6. a root routing-table CLAUDE.md states the cross-language constraints
    7. the core and every discovered host has its own CLAUDE.md
  WARN (⚠ advisory):
    8. no host hand-mirrors a uniffi-exported core type
    9. a versions.toml pins the toolchain + generator matrix
   10. reminder to run each sibling skill's own check_conformance.py

Usage:
    python check_conformance.py [REPO_ROOT]   # default: .
    python check_conformance.py REPO_ROOT --json

Exit code 0 = all HARD checks pass (warnings never fail). Non-zero = a HARD seam
invariant is violated. Pure stdlib (argparse, pathlib, tomllib, re, subprocess, json);
defensive — a malformed TOML or missing dir degrades to a ✗/⚠, never a crash.
"""
from __future__ import annotations

import argparse
import fnmatch
import json
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path

# ── Walk pruning ──────────────────────────────────────────────────────────────
# Heavy / build / vendored dirs we never descend (also avoids following the `target`
# symlink to an external volume). Pruned by exact directory name at any depth.
PRUNE_DIRS = frozenset({
    ".git", "target", "node_modules", ".gradle", "build", "DerivedData",
    ".build", "dist", "Pods", ".venv", "venv", "env", "__pycache__", ".next",
    ".turbo", "vendor", ".idea", ".swiftpm", "out", ".cargo", ".cxx", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "Carthage", "xcuserdata", ".tox",
})

# Source extensions worth scanning for a "this file is generated" header.
GEN_SCAN_EXTS = frozenset({
    ".swift", ".kt", ".kts", ".py", ".pyi", ".h", ".hpp", ".java",
    ".m", ".mm", ".c", ".cpp", ".go", ".cs",
})

# Markers that a host-language file is machine-generated (UniFFI / cbindgen / protoc / …).
GEN_MARKER = re.compile(
    r"autogenerated by|automatically generated|machine[- ]generated|"
    r"code generated by|@generated|do not edit",
    re.IGNORECASE,
)

# Strong evidence that a root CLAUDE.md is a cross-language *routing table* and not just
# a component list (check 6). Bare mentions of "binding"/"uniffi" do NOT qualify.
SEAM_PHRASES = (
    "single source of truth", "canonical core", "source of truth", "hand-mirror",
    "hand mirror", "hand-copy", "hand copy", "derived binding", "thin host",
    "composed gate", "freshness", "never reimplement", "唯一来源", "单一来源",
    "事实来源", "规范核心", "唯一真相", "瘦客户端", "组合门",
)

# Host language detection markers → host language label.
HOST_MARKERS = {
    "swift": ("Package.swift", "project.yml"),          # + any *.xcodeproj
    "python": ("pyproject.toml", "setup.py"),
    "kotlin": ("build.gradle", "build.gradle.kts", "settings.gradle", "settings.gradle.kts"),
}

GEN_EXT_HOST_LANG = {".swift": "swift", ".kt": "kotlin", ".kts": "kotlin",
                     ".py": "python", ".pyi": "python"}

SYMBOL = {"pass": "✓", "fail": "✗", "warn": "⚠", "info": "·"}


# ── Result model ──────────────────────────────────────────────────────────────
@dataclass
class Check:
    num: int
    title: str
    hard: bool
    status: str = "pass"          # pass | fail | warn
    detail: str = ""
    lines: list[str] = field(default_factory=list)

    def fail(self, detail: str) -> "Check":
        self.status = "fail" if self.hard else "warn"
        self.detail = detail
        return self

    def warn(self, detail: str) -> "Check":
        self.status = "warn"
        self.detail = detail
        return self

    def ok(self, detail: str) -> "Check":
        self.status = "pass"
        self.detail = detail
        return self


@dataclass
class Host:
    path: Path
    lang: str


# ── Filesystem helpers (defensive) ────────────────────────────────────────────
def walk_files(root: Path):
    """Yield files under root, pruning heavy/build dirs and never following symlinked dirs."""
    stack = [root]
    while stack:
        d = stack.pop()
        try:
            entries = list(d.iterdir())
        except (OSError, PermissionError):
            continue
        for e in entries:
            try:
                if e.is_symlink():
                    continue
                if e.is_dir():
                    if e.name not in PRUNE_DIRS:
                        stack.append(e)
                elif e.is_file():
                    yield e
            except OSError:
                continue


def load_toml(path: Path) -> dict | None:
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError, UnicodeDecodeError):
        return None


def read_head(path: Path, limit: int = 4096) -> str:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            return fh.read(limit)
    except OSError:
        return ""


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


def rel(root: Path, p: Path) -> str:
    try:
        return p.relative_to(root).as_posix()
    except ValueError:
        return p.as_posix()


# ── Discovery ─────────────────────────────────────────────────────────────────
def discover_workspaces(root: Path) -> list[Path]:
    """Every directory holding a Cargo.toml with a [workspace] table."""
    found: list[Path] = []
    for f in walk_files(root):
        if f.name != "Cargo.toml":
            continue
        data = load_toml(f)
        if data and "workspace" in data:
            found.append(f.parent)
    found.sort(key=lambda p: len(p.parts))   # shallowest (root) first
    return found


def discover_generated(root: Path) -> list[Path]:
    out: list[Path] = []
    for f in walk_files(root):
        if f.suffix.lower() not in GEN_SCAN_EXTS:
            continue
        if GEN_MARKER.search(read_head(f)):
            out.append(f)
    out.sort()
    return out


def discover_hosts(root: Path, core_dirs: set[Path]) -> list[Host]:
    """Find Swift/Python/Kotlin host roots. Once a host root is found we don't descend
    into it (so android/ counts once, not android/app/ too). The bare workspace root is
    not a host."""
    hosts: list[Host] = []
    seen: set[Path] = set()
    stack = [root]
    while stack:
        d = stack.pop()
        if d in seen:
            continue
        seen.add(d)
        lang = host_lang_of(d)
        # Don't classify the core/workspace root itself as a host even if it has stray markers.
        if lang and d not in core_dirs:
            hosts.append(Host(d, lang))
            continue   # prune: don't descend into a host root
        try:
            children = [c for c in d.iterdir()
                        if c.is_dir() and not c.is_symlink() and c.name not in PRUNE_DIRS]
        except OSError:
            children = []
        stack.extend(children)
    hosts.sort(key=lambda h: h.path.as_posix())
    return hosts


def host_lang_of(d: Path) -> str | None:
    try:
        names = {c.name for c in d.iterdir()}
    except OSError:
        return None
    # Swift: explicit markers or any .xcodeproj bundle.
    if names & set(HOST_MARKERS["swift"]) or any(n.endswith(".xcodeproj") for n in names):
        return "swift"
    if names & set(HOST_MARKERS["python"]):
        return "python"
    if names & set(HOST_MARKERS["kotlin"]):
        return "kotlin"
    return None


def owning_host(hosts: list[Host], f: Path) -> Host | None:
    best: Host | None = None
    for h in hosts:
        try:
            f.relative_to(h.path)
        except ValueError:
            continue
        if best is None or len(h.path.parts) > len(best.path.parts):
            best = h
    return best


# ── .gitattributes coverage ───────────────────────────────────────────────────
def gitattributes_patterns(root: Path) -> list[str]:
    """Return path patterns (relative to root) marked linguist-generated."""
    pats: list[str] = []
    ga = root / ".gitattributes"
    if not ga.is_file():
        return pats
    for line in read_text(ga).splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            continue
        pat, attrs = parts[0], parts[1:]
        if any(a in ("linguist-generated", "linguist-generated=true") for a in attrs):
            pats.append(pat)
    return pats


def _pattern_to_regex(pat: str) -> re.Pattern:
    p = pat[1:] if pat.startswith("/") else pat
    out, i = [], 0
    while i < len(p):
        c = p[i]
        if p.startswith("**/", i):
            out.append(r"(?:.*/)?")
            i += 3
        elif p.startswith("**", i):
            out.append(r".*")
            i += 2
        elif c == "*":
            out.append(r"[^/]*")
            i += 1
        elif c == "?":
            out.append(r"[^/]")
            i += 1
        else:
            out.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(out) + "$")


def gitattr_covers(patterns: list[str], relpath: str) -> bool:
    base = relpath.rsplit("/", 1)[-1]
    for pat in patterns:
        if "/" not in pat.rstrip("/"):
            # No slash → match against basename at any depth.
            if fnmatch.fnmatch(base, pat):
                return True
            continue
        rx = _pattern_to_regex(pat)
        if rx.match(relpath):
            return True
        # Lenient: a non-anchored "**"-style pattern may match a suffix of the path.
        if pat.startswith("**") and rx.search(relpath):
            return True
    return False


# ── Lint-config exclusion (check 3b) ──────────────────────────────────────────
def lint_excluded(host: Host, root: Path, gen: Path) -> tuple[bool, str]:
    """(excluded, explanation). 'excluded' means a lint/format CONFIG excludes the file
    (inline `disable` comments are noted but do not satisfy the standard)."""
    name = gen.name
    try:
        rel_to_host = gen.relative_to(host.path).as_posix()
    except ValueError:
        rel_to_host = name
    needles = {name, rel_to_host}
    # also any parent dir segment relative to host (e.g. "Generated", "RustLib")
    segs = [s for s in rel_to_host.split("/")[:-1] if s]

    if host.lang == "swift":
        cfgs = [host.path / ".swiftlint.yml", host.path / ".swiftlint.yaml",
                root / ".swiftlint.yml", host.path / ".swift-format", root / ".swift-format"]
        present = [c for c in cfgs if c.is_file()]
        if not present:
            inline = "swiftlint:disable" in read_head(gen)
            extra = " (file has inline `swiftlint:disable`, but the standard requires config-level exclusion)" if inline else ""
            return False, f"no SwiftLint/swift-format config in {rel(root, host.path)} or repo root{extra}"
        for c in present:
            blob = read_text(c)
            if any(n in blob for n in needles) or any(s in blob for s in segs):
                return True, f"excluded in {rel(root, c)}"
        return False, f"present in {', '.join(rel(root, c) for c in present)} but does not exclude {name}"

    if host.lang == "python":
        excludes = _ruff_excludes(host.path)
        if excludes is None:
            return False, f"no ruff config ([tool.ruff] / ruff.toml) found in {rel(root, host.path)}"
        if any(n in pat or pat in rel_to_host for pat in excludes for n in needles) \
                or any(s in pat for pat in excludes for s in segs):
            return True, "excluded in ruff config"
        return False, f"ruff config present but does not exclude {name}"

    if host.lang == "kotlin":
        cfgs = [host.path / "detekt.yml", host.path / "config" / "detekt" / "detekt.yml",
                host.path / ".editorconfig",
                host.path / "build.gradle.kts", host.path / "build.gradle",
                host.path / "app" / "build.gradle.kts", host.path / "app" / "build.gradle"]
        present = [c for c in cfgs if c.is_file()]
        for c in present:
            blob = read_text(c)
            if any(n in blob for n in needles) or any(s in blob for s in segs) or "uniffi" in blob.lower():
                return True, f"excluded in {rel(root, c)}"
        if not present:
            return False, f"no detekt/ktlint/gradle config found in {rel(root, host.path)}"
        return False, f"detekt/ktlint/gradle config present but does not exclude {name}"

    return True, "non-linted artifact"


def _ruff_excludes(host_dir: Path) -> list[str] | None:
    for name in ("ruff.toml", ".ruff.toml"):
        data = load_toml(host_dir / name)
        if data is not None:
            ex = data.get("exclude", []) + data.get("extend-exclude", [])
            return [str(x) for x in ex]
    py = load_toml(host_dir / "pyproject.toml")
    if py is not None:
        ruff = py.get("tool", {}).get("ruff", {})
        if ruff:
            ex = ruff.get("exclude", []) + ruff.get("extend-exclude", [])
            return [str(x) for x in ex]
    return None


# ── Generator pinned (check 2) ────────────────────────────────────────────────
def generator_pins(workspace: Path) -> dict[str, str]:
    """Map generator name → version string found pinned in the workspace's Cargo.toml(s)."""
    pins: dict[str, str] = {}
    tomls = [workspace / "Cargo.toml"]
    members = (load_toml(workspace / "Cargo.toml") or {}).get("workspace", {}).get("members", [])
    for m in members:
        # member may be a glob like "crates/*"
        for cand in workspace.glob(m + "/Cargo.toml") if "*" in m else [workspace / m / "Cargo.toml"]:
            tomls.append(cand)
    # also any Cargo.toml directly under the workspace (covers non-listed members)
    for f in walk_files(workspace):
        if f.name == "Cargo.toml":
            tomls.append(f)
    seen = set()
    for t in tomls:
        if t in seen or not t.is_file():
            continue
        seen.add(t)
        data = load_toml(t)
        if not data:
            continue
        tables = [data.get("dependencies", {}), data.get("build-dependencies", {}),
                  data.get("workspace", {}).get("dependencies", {})]
        for table in tables:
            for gen in ("uniffi", "pyo3"):
                if gen in pins:
                    continue
                spec = table.get(gen)
                ver = _dep_version(spec)
                if ver:
                    pins[gen] = ver
    return pins


def _dep_version(spec) -> str | None:
    if isinstance(spec, str):
        v = spec.strip()
        return v if v and v != "*" else None
    if isinstance(spec, dict):
        v = str(spec.get("version", "")).strip()
        return v if v and v != "*" else None
    return None


# ── Composed gate + freshness (checks 4,5) ────────────────────────────────────
def find_gate(root: Path) -> Path | None:
    for n in ("Makefile", "makefile", "justfile", "Justfile", "ci.sh"):
        if (root / n).is_file():
            return root / n
    return None


def find_freshness_guard(root: Path) -> Path | None:
    for cand in [root / "scripts" / "check_bindings.sh", root / "check_bindings.sh",
                 root / "scripts" / "check-bindings.sh"]:
        if cand.is_file():
            return cand
    # any shell script that regenerates then `git diff --exit-code`s
    for f in walk_files(root):
        if f.suffix != ".sh":
            continue
        blob = read_text(f).lower()
        if "git diff --exit-code" in blob and re.search(r"uniffi|gen[-_]binding|generate", blob):
            return f
    return None


# ── Hand-mirror detection (check 8) ───────────────────────────────────────────
def core_exported_types(workspace: Path) -> set[str]:
    rx = re.compile(
        r"#\[derive\([^)]*uniffi::(?:Record|Enum)[^)]*\)\][\s\S]{0,200}?"
        r"\bpub\s+(?:struct|enum)\s+([A-Z]\w+)",
    )
    types: set[str] = set()
    for f in walk_files(workspace):
        if f.suffix != ".rs":
            continue
        for m in rx.finditer(read_text(f)):
            types.add(m.group(1))
    return types


def host_decl_collisions(host: Host, types: set[str], generated: set[Path]) -> list[tuple[str, str]]:
    if not types:
        return []
    exts = {"swift": {".swift"}, "kotlin": {".kt", ".kts"}, "python": {".py"}}[host.lang]
    decl = re.compile(r"\b(?:data\s+class|final\s+class|public\s+(?:struct|class)|struct|class|enum)\s+([A-Z]\w+)")
    hits: list[tuple[str, str]] = []
    for f in walk_files(host.path):
        if f.suffix not in exts or f in generated:
            continue
        if GEN_MARKER.search(read_head(f)):
            continue
        for m in decl.finditer(read_text(f)):
            if m.group(1) in types:
                hits.append((m.group(1), f.name))
    # dedupe
    seen, out = set(), []
    for t, fn in hits:
        if (t, fn) not in seen:
            seen.add((t, fn))
            out.append((t, fn))
    return out


# ── The checks ────────────────────────────────────────────────────────────────
def run_checks(root: Path) -> tuple[list[Check], dict]:
    checks: list[Check] = []
    info: dict = {}

    workspaces = discover_workspaces(root)
    core = workspaces[0] if workspaces else None
    core_dirs = set(workspaces)
    hosts = discover_hosts(root, core_dirs)
    generated = discover_generated(root)
    info["workspaces"] = [rel(root, w) for w in workspaces]
    info["hosts"] = [{"path": rel(root, h.path), "lang": h.lang} for h in hosts]
    info["generated"] = [rel(root, g) for g in generated]

    # 1 — canonical core
    c = Check(1, "Canonical core (Cargo workspace) identified", hard=True)
    if not workspaces:
        c.fail("no Cargo.toml with a [workspace] table found anywhere in the repo")
    elif len(workspaces) == 1:
        c.ok(f"single workspace: {rel(root, core)}/Cargo.toml")
    else:
        c.warn(f"{len(workspaces)} workspaces found; treating shallowest as core: {rel(root, core)}")
        c.lines = [f"workspace: {w}/Cargo.toml" for w in info["workspaces"]]
    checks.append(c)

    # 2 — generator pinned
    c = Check(2, "Binding generator (uniffi/pyo3) pinned in the core", hard=True)
    if core is None:
        c.fail("no core workspace to inspect")
    else:
        pins = generator_pins(core)
        if pins:
            c.ok("pinned: " + ", ".join(f"{k}={v}" for k, v in sorted(pins.items())))
        else:
            c.fail(f"neither uniffi nor pyo3 found with a pinned version in {rel(root, core)}'s Cargo.toml(s)")
    checks.append(c)

    # 3 — generated bindings governed (linguist-generated AND lint-excluded)
    c = Check(3, "Generated bindings are governed (linguist-generated + gate-excluded)", hard=True)
    ga = gitattributes_patterns(root)
    if not generated:
        c.warn("no generated binding files discovered (no host-language file carries a generated-by header)")
    else:
        any_bad = False
        for g in generated:
            relp = rel(root, g)
            covered = gitattr_covers(ga, relp)
            lang = GEN_EXT_HOST_LANG.get(g.suffix.lower())
            host = owning_host(hosts, g) if lang else None
            parts = []
            ok_a = covered
            parts.append(("✓" if covered else "✗") + " linguist-generated")
            if lang and host is not None:
                excl, why = lint_excluded(host, root, g)
                parts.append(("✓" if excl else "✗") + f" gate-excluded ({why})")
                ok_b = excl
            elif lang and host is None:
                parts.append("· gate-exclude n/a (core-staged artifact, not under a host)")
                ok_b = True
            else:
                parts.append("· gate-exclude n/a (non-linted header)")
                ok_b = True
            if not (ok_a and ok_b):
                any_bad = True
            c.lines.append(f"{relp} — " + "; ".join(parts))
        if any_bad:
            if not ga:
                c.fail("at least one generated binding is not linguist-generated and/or not gate-excluded "
                       "(no .gitattributes found — add linguist-generated rules + lint excludes)")
            else:
                c.fail("at least one generated binding is not linguist-generated and/or not gate-excluded")
        else:
            c.ok(f"all {len(generated)} generated bindings are linguist-generated and gate-excluded")
    checks.append(c)

    # 4 — composed gate
    c = Check(4, "Composed gate chains core + host + binding-freshness", hard=True)
    gate = find_gate(root)
    if gate is None:
        c.fail("no Makefile / justfile / ci.sh at the repo root to host a composed gate")
    else:
        blob = read_text(gate)
        low = blob.lower()
        is_make = gate.name.lower() in ("makefile",) or gate.name.lower().endswith("justfile")
        has_check = (not is_make) or bool(re.search(r"(?m)^check\b\s*:?", blob)) or "check:" in low
        has_core = bool(re.search(r"cargo|check-core|core/ci|core/\.?ci|rust-project-standard", low))
        has_host = bool(re.search(r"xcodebuild|swift build|swift test|check-apple|check-python|"
                                  r"check-host|pytest|gradlew|gradle|ci\.sh", low))
        has_fresh = bool(re.search(r"check[-_]bindings|gen[-_]bindings|git diff --exit-code", low))
        missing = []
        if not has_check:
            missing.append("a `check` target")
        if not has_core:
            missing.append("a core check (cargo / check-core)")
        if not has_host:
            missing.append("a host check (swift/python/kotlin gate)")
        if not has_fresh:
            missing.append("a binding-freshness step (check-bindings / git diff --exit-code)")
        if missing:
            c.fail(f"{rel(root, gate)} is missing: " + "; ".join(missing))
        else:
            c.ok(f"{rel(root, gate)} chains core + host + binding-freshness")
    checks.append(c)

    # 5 — binding-freshness guard
    c = Check(5, "Binding-freshness drift guard exists and is wired into the gate", hard=True)
    guard = find_freshness_guard(root)
    if guard is None:
        c.fail("no check_bindings.sh (nor a regen + `git diff --exit-code` step) found")
    else:
        referenced = False
        if gate is not None:
            gblob = read_text(gate).lower()
            stem = guard.stem.lower()
            referenced = (stem in gblob) or ("check-bindings" in gblob) or ("check_bindings" in gblob)
        if referenced:
            c.ok(f"{rel(root, guard)} exists and is referenced by {rel(root, gate)}")
        else:
            c.fail(f"{rel(root, guard)} exists but is NOT referenced by the composed gate "
                   f"({rel(root, gate) if gate else 'no gate'}) — wire it in")
    checks.append(c)

    # 6 — root routing-table CLAUDE.md
    c = Check(6, "Root routing-table CLAUDE.md states cross-language constraints", hard=True)
    root_claude = root / "CLAUDE.md"
    if not root_claude.is_file():
        c.fail("no CLAUDE.md at the repo root")
    else:
        text = read_text(root_claude).lower()
        if any(p in text for p in SEAM_PHRASES):
            c.ok("present and states the seam constraints (single source of truth / canonical core / …)")
        else:
            c.fail("CLAUDE.md exists but does not read as a cross-language routing table "
                   "(no 'single source of truth' / 'canonical core' / 'derived bindings' / 'composed gate' language)")
    checks.append(c)

    # 7 — per-sub-tree CLAUDE.md
    c = Check(7, "Core and every host has its own CLAUDE.md", hard=True)
    missing = []
    subtrees: list[Path] = []
    if core is not None:
        subtrees.append(core)
    subtrees += [h.path for h in hosts]
    for d in subtrees:
        if not (d / "CLAUDE.md").is_file():
            missing.append(rel(root, d) or ".")
    for d in subtrees:
        tag = "core" if d == core else "host"
        mark = "✓" if (d / "CLAUDE.md").is_file() else "✗"
        c.lines.append(f"{mark} {tag}: {rel(root, d) or '.'}/CLAUDE.md")
    if missing:
        c.fail("missing CLAUDE.md in: " + ", ".join(missing))
    else:
        c.ok(f"all {len(subtrees)} sub-trees have a CLAUDE.md")
    checks.append(c)

    # 8 — no hand-mirrored core structs (WARN)
    c = Check(8, "No host hand-mirrors a uniffi-exported core type", hard=False)
    types = core_exported_types(core) if core is not None else set()
    if not types:
        c.ok("no uniffi Record/Enum exports detected to compare against (or no core)")
    else:
        gen_set = set(generated)
        suspects = []
        for h in hosts:
            for tname, fn in host_decl_collisions(h, types, gen_set):
                suspects.append(f"{rel(root, h.path)} re-declares `{tname}` (in {fn})")
        if suspects:
            c.warn(f"{len(suspects)} possible hand-mirror(s) of a core type — verify these aren't re-implementations")
            c.lines = suspects[:20]
        else:
            c.ok(f"no host re-declares any of the {len(types)} uniffi-exported core types")
    checks.append(c)

    # 9 — versions.toml (WARN)
    c = Check(9, "versions.toml pins the toolchain + generator matrix", hard=False)
    if (root / "versions.toml").is_file():
        c.ok("versions.toml present")
    else:
        c.warn("no versions.toml — recommend adding the single toolchain+generator matrix the gate/CI read")
    checks.append(c)

    # 10 — delegation reminder (WARN/info)
    c = Check(10, "Delegate per-language internals to the sibling checkers", hard=False)
    c.status = "info"
    c.detail = "this checker covers SEAMS only; run each sub-tree's own check_conformance.py for internals"
    skills = Path.home() / ".claude" / "skills"
    sib = {"rust": skills / "rust-project-standard" / "scripts" / "check_conformance.py",
           "swift": skills / "swift-project-standard" / "scripts" / "check_conformance.py",
           "python": skills / "python-project-standard" / "scripts" / "check_conformance.py"}
    if core is not None and sib["rust"].is_file():
        c.lines.append(f"core   → python {sib['rust']} {rel(root, core) or '.'}")
    lang_host = {}
    for h in hosts:
        lang_host.setdefault(h.lang, h.path)
    for lang, hp in lang_host.items():
        s = sib.get(lang)
        if s and s.is_file():
            c.lines.append(f"{lang:<6} → python {s} {rel(root, hp)}")
    if not c.lines:
        c.lines.append("(sibling checkers not found under ~/.claude/skills/*/scripts/)")
    checks.append(c)

    return checks, info


# ── Reporting ─────────────────────────────────────────────────────────────────
def print_report(root: Path, checks: list[Check], info: dict) -> int:
    print("═" * 72)
    print("  SEAM CONFORMANCE — polyglot-core-standard")
    print(f"  repo: {root}")
    print("═" * 72)

    print("\n▸ Discovery")
    print(f"  core workspace(s): {', '.join(info['workspaces']) or '(none)'}")
    if info["hosts"]:
        print("  hosts:")
        for h in info["hosts"]:
            print(f"    · {h['lang']:<7} {h['path']}")
    else:
        print("  hosts: (none discovered)")
    print(f"  generated bindings: {len(info['generated'])} file(s)")

    def emit(title: str, group: list[Check]) -> None:
        print(f"\n▸ {title}")
        for c in group:
            sym = SYMBOL.get(c.status, "·")
            print(f"  {sym} [{c.num}] {c.title}")
            if c.detail:
                print(f"        {c.detail}")
            for ln in c.lines:
                print(f"          - {ln}")

    emit("Hard invariants", [c for c in checks if c.hard])
    emit("Advisory", [c for c in checks if not c.hard])

    passed = sum(1 for c in checks if c.status == "pass")
    failed = sum(1 for c in checks if c.status == "fail")
    warned = sum(1 for c in checks if c.status == "warn")
    print("\n" + "─" * 72)
    print(f"  {passed} passed, {failed} failed, {warned} warnings")
    if failed:
        print("  ✗ HARD seam invariant(s) violated — this repo does not yet conform.")
    else:
        print("  ✓ all hard seam invariants satisfied (warnings are advisory).")
    print("─" * 72)
    return 1 if failed else 0


def to_json(checks: list[Check], info: dict, code: int) -> dict:
    return {
        "discovery": info,
        "checks": [
            {"num": c.num, "title": c.title, "hard": c.hard,
             "status": c.status, "detail": c.detail, "lines": c.lines}
            for c in checks
        ],
        "summary": {
            "passed": sum(1 for c in checks if c.status == "pass"),
            "failed": sum(1 for c in checks if c.status == "fail"),
            "warnings": sum(1 for c in checks if c.status == "warn"),
            "exit_code": code,
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Verify the cross-language SEAM invariants of a polyglot-core monorepo "
                    "(polyglot-core-standard). Per-language internals are delegated to the "
                    "rust/swift/python-project-standard sibling checkers.")
    ap.add_argument("repo_root", nargs="?", default=".", help="repo root (default: .)")
    ap.add_argument("--json", action="store_true", help="emit a machine-readable JSON summary")
    args = ap.parse_args()

    root = Path(args.repo_root).resolve()
    if not root.is_dir():
        msg = f"not a directory: {root}"
        if args.json:
            print(json.dumps({"error": msg, "summary": {"exit_code": 2}}, ensure_ascii=False, indent=2))
        else:
            print(f"✗ {msg}")
        return 2

    try:
        checks, info = run_checks(root)
    except Exception as exc:  # never crash on a weird repo — degrade to a hard error
        msg = f"internal error while checking {root}: {exc!r}"
        if args.json:
            print(json.dumps({"error": msg, "summary": {"exit_code": 2}}, ensure_ascii=False, indent=2))
        else:
            print(f"✗ {msg}")
        return 2

    failed = sum(1 for c in checks if c.status == "fail")
    code = 1 if failed else 0
    if args.json:
        print(json.dumps(to_json(checks, info, code), ensure_ascii=False, indent=2))
        return code
    return print_report(root, checks, info)


if __name__ == "__main__":
    raise SystemExit(main())
